
server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_atto_research?characterEncoding=UTF-8&serverTimezone=UTC
    username: test
    password: testtest123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB